config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root 'welcomes#index'
  resources :tags, only: [:index, :show]
  resources :categories, only: [:index, :show] 
  resources :organisations, except: :index , path: '/company' do
    resources :products
  end

  resources :managers,  only: [:index, :show]
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :products, dependent: :destroy

  mount_uploader :organisation, OrganisationUploader
  
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  def slug_candidates
    [
      :name,
      [:name, :city],
      [:name, :street, :city],
      [:name, :street, :city, :state]
    ]
  end

  validates :user, :name, :email, :street, :postcode, :city, :state, :phone_number, 
  :description, :slug, :category, :organisation, presence: true

  def location
    "#{city.capitalize}, #{state.capitalize} "
  end
end

app/controllers/admin/organisations_controller.rb
module Admin
  class OrganisationsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Organisation.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Organisation.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:show]
  before_action :authenticate_owner, only: [:edit, :update, :destroy]


  def show
    @categories = Category.all
    if @organisation.category
      @companies = @organisation.category.organisations.limit(3).order('RANDOM()')
    else
      @companies = Organisation.limit(3).order('RANDOM()')
    end
  end

  def new
    @organisation = Organisation.new
  end

  def edit
  end

  def create
    @organisation = current_user.organisations.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @organisation.destroy
    respond_to do |format|
      format.html { redirect_to managers_path, notice: 'Organisation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def authenticate_owner
      redirect_to sign_in_path unless @organisation.user_id == current_user.id
    end

    def set_organisation
      @organisation = Organisation.friendly.find(params[:id])
    end


    def organisation_params
      params.require(:organisation).permit(:name, :email, :street, :city, :postcode, :state, :phone_number, :description, :website, :facebook, :instagram, :twitter, :organisation)
    end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/organisations/_form.html.erb
<%= simple_form_for(@organisation, html: { multipart: true }) do |f| %>
  <% if @organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
      <% @organisation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="info-block">
    <div class="form-group">
      <%= f.input :name%>
    </div>
    <div class="form-group">
      <%= f.input :description %>
    </div>
    <div class="form-group">
      <%= f.association :category%>
    </div>
  </div>
  <div class="info-block">
    <h3>Contact & Address</h3>
    <hr>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :email %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :phone_number %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :street %>
        </div>
      </div>
      <div class="col-md-6">
      <div class="form-group">
          <%= f.input :city %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :postcode %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :state %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="info-block">
    <h3>Website & Social media</h3>
    <hr>
    <div class="row info-block">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :website %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :facebook %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <div class="form-group">
        <%= f.input :twitter %>
      </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :instagram %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.input :organisation, label: "Company logo" %>
      </div>
    </div>
  </div>


  <div class="form-group clearfix">
    <%= f.button :submit, "Submit", class: "btn pull-right btn-default" %>
  </div>
<% end %>

<style>
  .info-block{
    padding-bottom: 20px;
  }
</style>

app/views/organisations/_show_grid.html.erb
<div class="col-md-3 col-sm-4">
  <div class="item">
    <div class="image">
      <div class="quick-view"><i class="fa fa-eye"></i><span>Quick View</span></div>
      <a href="<%= organisation_path(organisation) %>">
        <div class="overlay">
          <div class="inner">
            <div class="content">
              <h4>Description</h4>
              <p><%= organisation.description %></p>
            </div>
          </div>
        </div>
        <div class="item-specific">
          <span title="Text"><%= organisation.name %></span>
        </div>
        <img src="<%= organisation.organisation.try(:url) || asset_path('item.jpg') %>" alt="">
      </a>
    </div>
    <div class="wrapper">
      <%= link_to(organisation_path(id: organisation.slug)) do %>
        <h3><%= organisation.name %></h3>
      <% end %>
      <figure><%= organisation.city %></figure>
    </div>
  </div>
  <!-- /.item-->
</div>
<!--/.col-sm-4-->

app/views/organisations/_show_list.html.erb
<div class="item list">
  <div class="image">
    <div class="quick-view"><i class="fa fa-eye"></i><span>Quick View</span></div>
    <a href="<%= organisation_path(organisation) %>">
      <div class="overlay">
        <div class="inner">
          <div class="content">
            <h4>Description</h4>
            <p><%= organisation.description %></p>
          </div>
        </div>
      </div>
      <div class="item-specific">

      </div>

      <img src="<%= organisation.organisation.try(:url) || asset_path("item.jpg") %>" alt="">
    </a>
  </div>
  <div class="wrapper">
    <a href="<%= organisation_path(organisation) %>"><h3><%= organisation.name.capitalize %></h3></a>
    <figure><%= organisation.location.capitalize %></figure>
    <div class="info">
      <div class="type">
        <span><%= organisation.category.name.capitalize %></span>
      </div>
    </div>
  </div>
</div>

app/views/organisations/_show_vertical.html.erb
<%= link_to(organisation_path(id: company.slug), class: "item-horizontal small") do %>
  <h3><%= company.name.capitalize %></h3>
  <figure><%= company.city.capitalize %></figure>
  <div class="wrapper">
    <div class="image"><%= image_tag("item.jpg") %></div>
    <div class="info">
      <div class="type">
        <span><%= company.category.name.capitalize %></span>
      </div>
    </div>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing Organisation</h1>

<%= render 'form' %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organisations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organisations.each do |organisation| %>
      <tr>
        <td><%= link_to 'Show', organisation %></td>
        <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
        <td><%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organisation', new_organisation_path %>

app/views/organisations/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>New Organisation</h1>

  <%= render 'form' %>
</div>

app/views/organisations/show.html.erb
<section class="container">
  <div class="row">
    <!--Company Detail Content-->
    <div class="col-md-9">
      <header>
        <h1 class="page-title"><%= @organisation.name %></h1>
      </header>
      <!--Logo and Map-->
      <section>
        <div class="row">
          <div class="col-md-4 col-sm-4">
            <div class="logo">
              <div class="image"><img src="<%= @organisation.organisation_url || asset_path('item.jpg') %>" alt=""> </div>
            </div>
          </div>
          <div class="col-md-8 col-sm-8">
            <div id="map-simple"></div>
          </div>
        </div>
      </section>
      <!--end Logo and Map-->
      <!--Contact info-->
      <section>
        <div class="row">
          <div class="col-md-4 col-sm-4">
            <section>
              <h3><i class="fa fa-map-marker"></i>Address</h3>
              <address>
                <div><%= @organisation.street.capitalize %></div>
                <div><%= @organisation.postcode %> <%= @organisation.city.capitalize %></div>
                <div><%= @organisation.city.capitalize %></div>
              </address>
            </section>
            <section>
              <h3><i class="fa fa-share-alt"></i>Social Profile</h3>
              <div class="social row">
                <%= link_to(@organisation.twitter, class: "social-button") do %>
                <i class="fa fa-twitter"></i>
                <% end %>
                <%= link_to(@organisation.facebook, class: "social-button") do %>
                <i class="fa fa-facebook"></i>
                <% end %>
                <%= link_to(@organisation.instagram, class: "social-button") do %>
                <i class="fa fa-instagram"></i>
                <% end %>
              </div>
            </section>
          </div>
          <div class="col-md-4 col-sm-4">
            <h3><i class="fa fa-envelope"></i>Contact</h3>
            <figure>
              <div class="info">
                <strong>Phone</strong><br>
                <span><%= @organisation.phone_number %></span>
              </div>
              <div class="info">
                <strong>Email</strong><br>
                <span><%= @organisation.email %></span>
              </div>
              <div class="info">
                <strong>Website</strong><br>
                <%= link_to(@organisation.website, @organisation.website) %>
              </div>
            </figure>
          </div>
          <div class="col-md-4 col-sm-4">
            <h3><i class="fa fa-file-text"></i>About Us</h3>
            <p>
              <%= @organisation.description %>
            </p>
          </div>
        </div>
      </section>
      <!--end Contact info-->
      <hr>
      
      <!--Company Items-->
      <section>
        <header><h2>Company Items</h2></header>
        <div id="company-items">
          <div class="content">
            <div class="row">
              <% @organisation.products.first(6).each do |product| %>
                <%= render 'products/show_grid', product: product %>
              <% end %>
            </div>
          </div>
        </div>

      </section>
      <!--end Company Items-->
    </div>
    <!-- /.col-md-8-->
    <!--Sidebar-->
    <div class="col-md-3">
      <aside id="sidebar">
        <section>
          <header><h2>In the same category</h2></header>
          <% @companies.each do |company| %>
            <%= render 'organisations/show_vertical', company: company %>
          <% end %>
          <!--/.item-horizontal small-->
        </section>
        <section>
          <%= render 'categories/categories' %>
        </section>
      </aside>
      <!-- /#sidebar-->
    </div>
    <!-- /.col-md-3-->
    <!--end Sidebar-->
  </div><!-- /.row-->
</section>
    <!-- /.container-->