config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root 'welcomes#index'
  resources :tags, only: [:index, :show]
  resources :categories, only: [:index, :show] 
  resources :organisations, except: :index , path: '/company' do
    resources :products
  end

  resources :managers,  only: [:index, :show]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :organisations
  
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Category.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Category.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.friendly.find(params[:id])
    @organisations = @category.organisations
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories.html.erb
<header><h2>Categories</h2></header>
<ul class="bullets">
  <% @categories.each do |category| %>
    <%= link_to(category_path(id: category.slug)) do %>
      <li><%= category.name.capitalize %></li>
    <% end %>
  <% end %>
</ul>

app/views/categories/index.html.erb
<div class="container">
  <section id="categories">
    <header><h2>Categories</h2></header>
    <% @categories.each do |category| %>
      <div class="col-md-3">
        <ul class="categories">
          <li class="category-list">
            <strong><%= link_to(category.name.capitalize, category_path(id: category.slug) ) %></strong> 
          </li>
        </ul>
      </div>
    <% end %>
  </section>
</div>

app/views/categories/show.html.erb
<header><h2><%= @category.name.capitalize %></h2></header>
<section class="block equal-height">
  <div class="row">
    <% @organisations.each do |organisation| %>
      <%= render 'organisations/show_grid', organisation: organisation %>
    <% end %>
  </div>
</section>